repos:
  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.2
    hooks:
      - id: autopep8
        args: [--in-place, --global-config=.github/setup.cfg]
        exclude: ^(\.git/|__pycache__/|venv/|.*\.(md|txt)$)

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.2
    hooks:
      - id: flake8
        args: [--config=.github/setup.cfg]
        exclude: ^(\.git/|__pycache__/|venv/|.*\.(md|txt)$)
        additional_dependencies:
          - flake8-docstrings