name: Check Code Formatting

# on:
#   push:
#     branches-ignore:
#       - staging
#   pull_request:
#     branches-ignore:
#       - staging 

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies for Formatting
        run: |
          pip install autopep8==2.3.2 flake8==7.1.2 flake8-docstrings

      - name: Check autopep8 Formatting
        # In diff mode to show what formatting changes should be applied
        run: |
          autopep8 --diff --recursive . --global-config .github/setup.cfg

      - name: Run flake8 Checks
        run: |
          flake8 --config .github/setup.cfg .
